package engine.graphics.environment;

import java.awt.Color;

import engine.camera.Camera;
import engine.graphics.models.Model;
import engine.graphics.triangle.Triangle;
import engine.matrix.Mat4x4;

/**
 * The {@code Skybox} class represents the sky box that surrounds the Camera creating the appearance of a sky. 
 * This is a large box that has a static global rotation and is always in the same position as the camera.
 * <p>
 * The {@code Engine} creates and uses only one {@code Skybox}.
 * 
 * @author Aidan
 * @since 1.1
 * 
 * @see Camera
 */
public class Skybox {
	private Model model;
	private Color color = Color.DARK_GRAY;
	
	/**
	 * Constructs a new Skybox given a model.
	 * 
	 * @param model	the model of the skybox
	 * 
	 * @see Model
	 */
	public Skybox(Model model) {
		this.model = model;
	}
	
	/**
	 * Projects all of the triangles of the skybox's model onto screen space.
	 * 
	 * @param camera	the main camera of the scene
	 * @param matView	the view matrix generated by the engine
	 * @param matProj	the projection matrix generated by the engine
	 * @param WIDTH		the width of the screen
	 * @param HEIGHT	the height of the screen
	 * @param light		the environmental light of the scene
	 * 
	 * @see Camera
	 * @see Mat4x4
	 * @see EnvironmentLight
	 */
	public void project(Camera camera, Mat4x4 matView, Mat4x4 matProj, int WIDTH, int HEIGHT, EnvironmentLight light) {
		Triangle.projectSkybox(this.model.mesh, camera, matView, matProj, WIDTH, HEIGHT, color);
	}
}
